config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :cocktails do
      resources :doses
    end
    resources :doses, only: [:destroy]

    root to: "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktails_url
    else
      render :new
    end
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktails_url
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_url
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <% if @cocktail.errors.any? %>
  <h3>OOps!!!! You have these errors:</h3>
  <ul>
    <% @cocktail.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <div class="form-inputs">
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>


  <div class="form-actions">
    <%= f.submit :submit, class: 'btn btn-primary '%>
  </div>
<% end %>

app/views/cocktails/index.html.erb
<%#= link_to "create cocktail", new_cocktail_path %>
<div><h1>Cocktails!</h1></div>


<%= link_to 'Create new cocktail', new_cocktail_path, class: 'btn btn-primary ' %>

<div class="cards">
<% @cocktails.each do |cktl| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path cktl.photo %>)">
    <%= link_to cktl.name, cktl %>
    <div>
      <% cktl.doses.each do |dose| %>
        <%= dose.ingredient.name %> (<%= dose.description %>) <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, dose, method: :delete, data: { confirm: 'Are you sure?' } %> <br>
      <% end %>
       <%= link_to 'Add ingredient (dose)', new_cocktail_dose_path(cktl) %>
    </div>
  </div>
<% end %>
</div>







<!-- <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Le Wagon Shanghai</h2>
    <p>Very cool city, the best</p>
  </div>
  <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
  <a class="card-link" href="#" ></a>
</div>
 -->

app/views/cocktails/new.html.erb
<h1>New cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<%= @cocktail.name %>
<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

<%= link_to 'back to list', cocktails_url %>

app/views/doses/new.html.erb
<h1>Add new dose to <%= @cocktail.name %></h1>
<%= link_to 'Go back to the cocktail list', cocktails_path %>

<%#= link_to "Go back to #{@cocktail.name}", @cocktail %>
<%#= link_to "Go back to #{@cocktail.name}", cocktail_path(@cocktail) %>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <div class="alert alert-danger " >
    <% @dose.errors.full_messages.each do |error| %>
      <p><%= error %></p>
    <% end %>
  </div>
  <%= f.association :ingredient %>
  <%#= f.input :ingredient, as: :select, collection: Ingredient.all %>
  <%= f.input :description %>
  <%= f.button :submit, class: 'btn btn-primary '%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2623&q=80');">
      <div class="container" >
        <%= yield %>
      </div>
    </div>


    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>